version: '3'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_management_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  setup:
    build: .
    command: bash -c "bundle install && bin/rails db:create db:migrate db:seed"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/project_management_development
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    command: bash -c "bundle install && bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - assets:/app/public/assets
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/project_management_development
    depends_on:
      setup:
        condition: service_completed_successfully

  assets:
    build: .
    command: bash -c "bundle install && bin/rails tailwindcss:build && bin/rails assets:precompile"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - assets:/app/public/assets
    environment:
      RAILS_ENV: development
    depends_on:
      - web

  tailwind:
    build: .
    command: bash -c "bundle install && bin/rails tailwindcss:watch"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - assets:/app/public/assets
    environment:
      RAILS_ENV: development
    depends_on:
      - assets

volumes:
  postgres_data:
  bundle:
  node_modules:
  assets: